# Generated by Django 2.1.2 on 2019-07-03 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_post_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_moderator_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_moderator_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyModeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate', models.IntegerField()),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_moderations', to=settings.AUTH_USER_MODEL)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderations', to='core.Reply')),
            ],
        ),
    ]
