# Generated by Django 2.1.2 on 2019-07-05 11:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_clipboarditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clipboarditem',
            unique_together={('owner', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='moderatorsubscription',
            unique_together={('subscriber', 'moderator')},
        ),
        migrations.AlterUniqueTogether(
            name='reply',
            unique_together={('to_post', 'reply_post')},
        ),
        migrations.AlterUniqueTogether(
            name='replymoderation',
            unique_together={('moderator', 'reply')},
        ),
    ]
